---
# tasks file for setup-user
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  sudo: yes

- name: Add sudoers users to wheel group
  user: 
    name: "{{ username }}" 
    groups: wheel 
    append: yes 
    state: present 
    createhome: yes
    password: "{{ default_password }}"
  sudo: yes

#Reference: http://stackoverflow.com/questions/37333305/ansible-create-a-user-with-sudo-privileges